language: node_js
node_js: 8

sudo: required

os:
  - linux
  - osx

env:
  global:
    - RW_VERSION=0.4-dev
  matrix:
    - OCAML_VERSION=4.02

cache:
  timeout: 360
  directories:
    - "$HOME/.esy"
    -
install:
  - travis_retry npm install -g esy
  - travis_wait esy install

script:
  - travis_wait 40 esy build
  - mkdir -p _build/final
  - esy exec-command cp "#{self.target_dir}/default/bin/rincewind.exe" _build/final/rincewind_w%OCAML_VERSION%-%RW_VERSION%.exe

deploy:
  provider: bintray
  file: descriptor.json
  user: giraud
  skip_cleanup: true
  key:
    secure: itdLWIxgaezQg/X8pwrHpl+2dxRCZvvqkTaqYMv8j1vX59m+cGrdCVHLmoWdbAGILL8zopVlqGLeOpFmrY1idBkVQHZ6z67kwNisHoulIDYX3bsBg/lF7Eo9uCCZEG3hKtPPXDx/BWvcbPdm7PQNkH/wRTFBcs7mpegspI1bD/76BKlbEkKpK/VKdgd8EMlnaiNpFHWeCuSa5hURxbkaPxjxgwh6gKI7/4RxfRQ4wKGe3ZIjaSpoUBTWB4Bgcz6GcvlJvBEjsPnWRPbeFd8C+EosVBx61UiqkN9Qq7UxdTN/yBzV+60GXFwwGoyd84RbZReBG14/3tPZUZpAGZj+rArxi78rwy9OBLVpS/N77gRh5wO9hGXeqJ6n7Fs4Mh7dLuCpwguFBL2F6VuJYOLVKKn6R3l2QyIRtnGw5+hjxaqTBLjC1d/mr+9JpJKX5AJ33HWSnOqG383dtkHMweYqjB6WezDq3e0RSNSYEAhyXBzo3lw4TSnrGsA5AE4OeZCORZHLxTX+uMTZpcl2sjKZrBUytHcXlUU2UqgszBPsgEbrhALxcRQv2jUjHY0zC+6tcHSeaBsVrquuz5+FLd4nmSEQlsNDW0d2zsRn1dpeFJW8BLy6xPm9s1Uq+EbhNWwIVGspcDjETTinvl5AqioFvPtOjyT/LsGhMtRvyTKZIBo=