language: c
sudo: required
os:
  - linux
  - osx
before_install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-ocaml.sh
install:
  - bash -ex .travis-ocaml.sh
env:
  - OCAML_VERSION=4.02 OPAM_SWITCH=4.02.3+buckle-master
before_script:
  - opam install jbuilder
script:
  - eval `opam config env` && jbuilder build rincewind.exe
  - mkdir -p _build/final
  - mv _build/default/rincewind.exe _build/final/rincewind-${OCAML_VERSION}-${TRAVIS_OS_NAME}.exe
deploy:
  provider: bintray
  file: descriptor.json
  user: giraud
  key:
    secure: itdLWIxgaezQg/X8pwrHpl+2dxRCZvvqkTaqYMv8j1vX59m+cGrdCVHLmoWdbAGILL8zopVlqGLeOpFmrY1idBkVQHZ6z67kwNisHoulIDYX3bsBg/lF7Eo9uCCZEG3hKtPPXDx/BWvcbPdm7PQNkH/wRTFBcs7mpegspI1bD/76BKlbEkKpK/VKdgd8EMlnaiNpFHWeCuSa5hURxbkaPxjxgwh6gKI7/4RxfRQ4wKGe3ZIjaSpoUBTWB4Bgcz6GcvlJvBEjsPnWRPbeFd8C+EosVBx61UiqkN9Qq7UxdTN/yBzV+60GXFwwGoyd84RbZReBG14/3tPZUZpAGZj+rArxi78rwy9OBLVpS/N77gRh5wO9hGXeqJ6n7Fs4Mh7dLuCpwguFBL2F6VuJYOLVKKn6R3l2QyIRtnGw5+hjxaqTBLjC1d/mr+9JpJKX5AJ33HWSnOqG383dtkHMweYqjB6WezDq3e0RSNSYEAhyXBzo3lw4TSnrGsA5AE4OeZCORZHLxTX+uMTZpcl2sjKZrBUytHcXlUU2UqgszBPsgEbrhALxcRQv2jUjHY0zC+6tcHSeaBsVrquuz5+FLd4nmSEQlsNDW0d2zsRn1dpeFJW8BLy6xPm9s1Uq+EbhNWwIVGspcDjETTinvl5AqioFvPtOjyT/LsGhMtRvyTKZIBo=
  skip_cleanup: true
  dry-run: false
