language: c
before_install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-ocaml.sh
install: bash -ex .travis-build.sh
env:
  - OCAML_VERSION=4.02
script:
  - ./build.sh
