image: Visual Studio 2017

platform:
  - x64

environment:
  HOME: C:\Users\appveyor
  RW_VERSION: 0.4-dev
  FORK_USER: ocaml
  FORK_BRANCH: master
  CYG_ROOT: C:\cygwin64
  PACKAGE: "rincewind"
  matrix:
    - OPAM_SWITCH: 4.02.3+mingw64c
      OCAML_VERSION: 4.02

cache:
  - C:\Users\appveyor\.esy
  - _esy
  - node_modules

init:
  - "echo System architecture: %PLATFORM%"
  - "echo Build folder is: %APPVEYOR_BUILD_FOLDER%"

install:
  # The x64 is required as a workaround for esy/esy#412
  - ps: Install-Product node 8 x64
  - npm install -g esy@0.4.9
  # Retry is necessary due to esy/esy#413 and esy/esy#414
  - appveyor-retry esy install

build_script:
  - mkdir _build\final
  - esy build
  - esy exec-command --include-build-env Rincewind cp "#{self.target_dir}/default/bin/rincewind.exe" _build\final\rincewind_w%OCAML_VERSION%-%RW_VERSION%.exe

artifacts:
  - path: _build\final\*.exe

deploy:
- provider: BinTray
  username: giraud
  api_key:
    secure: KVeTN/0Ppyeluj5I28K9COpyZp/yKembWiEy9PyQawdfWXFwVlZXwOI5VZ/6QCZP
  subject: giraud
  repo: ocaml
  package: rincewind
  version: ${rw_version}
  publish: true
  override: true