environment:
  RW_VERSION: 0.4-dev
  PACKAGE: "rincewind"
  matrix:
  - OCAML_BRANCH: 4.02
  - OCAML_BRANCH: 4.06

install:
- appveyor DownloadFile "https://raw.githubusercontent.com/Chris00/ocaml-appveyor/master/install_ocaml.cmd" -FileName "C:\install_ocaml.cmd"
- C:\install_ocaml.cmd

build_script:
- cd "%APPVEYOR_BUILD_FOLDER%"
- jbuilder subst
- jbuilder install -y cppo
- jbuilder build -p rincewind.exe

after_build:
  - cmd: mkdir _build\final
  - cmd: copy _build\default\rincewind.exe _build\final\rincewind_w%OCAML_BRANCH%-%RW_VERSION%.exe

artifacts:
  - path: _build\final\*.exe

deploy:
- provider: BinTray
  username: giraud
  api_key:
    secure: KVeTN/0Ppyeluj5I28K9COpyZp/yKembWiEy9PyQawdfWXFwVlZXwOI5VZ/6QCZP
  subject: giraud
  repo: ocaml
  package: rincewind
  version: ${rw_version}
  publish: true
  override: true