platform:
  - x86

environment:
  FORK_USER: ocaml
  FORK_BRANCH: master
  CYG_ROOT: C:\cygwin64
  PACKAGE: "rincewind"
  DEPOPTS: "jbuilder"
  matrix:
    - OPAM_SWITCH: 4.02.3+mingw64c

init:
  - "echo System architecture: %PLATFORM%"

install:
  - ps: iex ((new-object net.webclient).DownloadString("https://raw.githubusercontent.com/$env:FORK_USER/ocaml-ci-scripts/$env:FORK_BRANCH/appveyor-install.ps1"))

build_script:
  - call %CYG_ROOT%\bin\bash.exe -l %APPVEYOR_BUILD_FOLDER%\appveyor-opam.sh
  - call %CYG_ROOT%\bin\bash.exe -lc "eval `opam config env` && opam install jbuilder && opam list && jbuilder build rincewind.exe"

after_build:
  - cmd: dir
  - cmd: mkdir _build\final
  - cmd: copy _build\default\rincewind.exe _build\final\rincewind-windows-4.02-0.2.exe

artifacts:
  - path: _build\final\*.exe
