platform:
  - x86

environment:
  RW_VERSION: 0.1
  FORK_USER: ocaml
  FORK_BRANCH: master
  CYG_ROOT: C:\cygwin64
  PACKAGE: "rincewind"
  matrix:
    - OPAM_SWITCH: 4.02.3+mingw64c
      OCAML_VERSION: 4.02

init:
  - "echo System architecture: %PLATFORM%"

install:
  - ps: iex ((new-object net.webclient).DownloadString("https://raw.githubusercontent.com/$env:FORK_USER/ocaml-ci-scripts/$env:FORK_BRANCH/appveyor-install.ps1"))

build_script:
  - call %CYG_ROOT%\bin\bash.exe -l %APPVEYOR_BUILD_FOLDER%\appveyor-opam.sh
  - call %CYG_ROOT%\bin\bash.exe -lc "cd c:/projects/rincewind && eval `opam config env` && opam install jbuilder && jbuilder build rincewind.exe"

after_build:
  - cmd: mkdir _build\final
  - cmd: copy _build\default\rincewind.exe _build\final\rincewind_w%OCAML_VERSION%-%RW_VERSION%.exe

artifacts:
  - path: _build\final\*.exe

deploy:
- provider: BinTray
  username: giraud
  api_key:
    secure: KVeTN/0Ppyeluj5I28K9COpyZp/yKembWiEy9PyQawdfWXFwVlZXwOI5VZ/6QCZP
  subject: giraud
  repo: ocaml
  package: rincewind
  version: ${rw_version}
  publish: true
  on:
    appveyor_repo_tag: true