image: Visual Studio 2017

platform:
  - x64

environment:
  HOME: C:\Users\appveyor
  RW_VERSION: 0.5-dev

cache:
  - C:\Users\appveyor\.esy
  - _esy
  - node_modules

install:
  # The x64 is required as a workaround for esy/esy#412
  - ps: Install-Product node 8 x64
  - npm install -g esy@0.4.9
  # Retry is necessary due to esy/esy#413 and esy/esy#414
  - appveyor-retry esy install

build_script:
  - mkdir _build\final
  - esy build
  - esy exec-command --include-build-env rincewind cp "#{self.target_dir}/default/bin/rincewind.exe" _build\final\rincewind_w%OCAML_VERSION%-%RW_VERSION%.exe

artifacts:
  - path: _build\final\*.exe

deploy:
- provider: BinTray
  username: giraud
  api_key:
    secure: KVeTN/0Ppyeluj5I28K9COpyZp/yKembWiEy9PyQawdfWXFwVlZXwOI5VZ/6QCZP
  subject: giraud
  repo: ocaml
  on:
      branch: 4.02
  package: rincewind
  version: ${rw_version}
  publish: true
  override: true