name: Build Rincewind executables

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        ocaml-compiler:
          - '4.14'
          - '4.13'
          - '4.12'
          - '4.11'
          - '4.10'
          - '4.09'
          - '4.08'
          - '4.06'

    runs-on: ${{ matrix.os }}

    env:
      version: '0.10'
      macOS:   'o'
      Windows: 'w'
      Linux:   'l'

    steps:
    - name: Checkout rincewind repository
      uses: actions/checkout@v3

    - name: Use OCaml ${{ matrix.ocaml-compiler }}
      uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: ${{ format('{0}{1}', matrix.ocaml-compiler, '.x') }}

    - run: opam pin add rincewind.dev -n .

    - run: opam depext -yt rincewind

    - run: opam install -t . --deps-only

    - run: opam exec -- dune build

    - run: opam exec -- dune runtest

    - run: mkdir -p _build/final
    - run: mv _build/default/bin/rincewind.exe _build/final/rincewind_${{ env[runner.os] }}${{ matrix.ocaml-compiler }}-${{ env.version }}.exe

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: rincewind
        path: _build/final
